"""add user system_instructions

Revision ID: 36d79f9b0558
Revises: 6343b363e6b1
Create Date: 2026-03-01 00:40:09.272090
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from fim_one.migrations.helpers import table_has_column


# revision identifiers, used by Alembic.
revision: str = '36d79f9b0558'
down_revision: Union[str, None] = '6343b363e6b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    if not table_has_column(bind, "users", "system_instructions"):
        op.add_column('users', sa.Column('system_instructions', sa.Text(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'system_instructions')
    # ### end Alembic commands ###
