"""v0.5 add kb_ids and grounding_config to agents

Revision ID: 6298f486b2f3
Revises: 37d8b9770839
Create Date: 2026-02-28 11:56:13.344523
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6298f486b2f3'
down_revision: Union[str, None] = '37d8b9770839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('kb_ids', sa.JSON(), nullable=True))
    op.add_column('agents', sa.Column('grounding_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'grounding_config')
    op.drop_column('agents', 'kb_ids')
    # ### end Alembic commands ###
